AWSTemplateFormatVersion: '2010-09-09'
Description: 'CodeBuild project for building Bedrock Gateway Docker image with local tiktoken caching'

Parameters:
  ProjectName:
    Type: String
    Default: bedrock-gateway-build
    Description: Name for the CodeBuild project
    
  GitHubRepoUrl:
    Type: String
    Default: https://github.com/aws-samples/bedrock-access-gateway.git
    Description: GitHub repository URL for the Bedrock Gateway source code
    
  GitHubBranch:
    Type: String
    Default: main
    Description: Git branch to build from
    
  ECRRepositoryName:
    Type: String
    Default: bedrock-gateway
    Description: Name of the ECR repository to create/use
    
  ImageTag:
    Type: String
    Default: latest
    Description: Docker image tag to use
    
  BuildArch:
    Type: String
    Default: linux/amd64
    AllowedValues:
      - linux/amd64
      - linux/arm64
    Description: Target architecture for the Docker build
    
  EnableMultiArch:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: Enable multi-architecture build (amd64 + arm64)

Conditions:
  IsMultiArch: !Equals [!Ref EnableMultiArch, "true"]

Resources:
  # ================================
  # ECR Repository
  # ================================
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ECRRepositoryName
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

  # ================================
  # CodeBuild Service Role
  # ================================
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonECR-FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: CodeBuildECRPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:PutImage
                Resource: '*'

  # ================================
  # CodeBuild Project
  # ================================
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      Description: !Sub "Build Bedrock Gateway Docker image with optimized tiktoken caching"
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: REPOSITORY_URI
            Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepositoryName}"
          - Name: IMAGE_TAG
            Value: !Ref ImageTag
          - Name: BUILD_ARCH
            Value: !Ref BuildArch
          - Name: ENABLE_MULTI_ARCH
            Value: !Ref EnableMultiArch
      Source:
        Type: GITHUB
        Location: !Ref GitHubRepoUrl
        BuildSpec: |
          version: 0.2
          phases:
            pre_build:
              commands:
                - echo Logging in to Amazon ECR...
                - aws --version
                - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
                - REPOSITORY_URI=$REPOSITORY_URI
                - IMAGE_TAG=$IMAGE_TAG
                - IMAGE_TAG_COMMIT=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
                - echo "Building image: $REPOSITORY_URI:$IMAGE_TAG"
                - echo "Commit tag: $REPOSITORY_URI:$IMAGE_TAG_COMMIT"
                - |
                  if [ "$ENABLE_MULTI_ARCH" = "true" ]; then
                    echo "Setting up multi-architecture build..."
                    docker buildx create --name multiarch-builder --use
                    docker buildx inspect --bootstrap
                  fi
                - |
                  # Pre-download tiktoken encodings locally for faster builds
                  echo "Pre-downloading tiktoken encodings..."
                  mkdir -p /tmp/tiktoken_cache
                  python3 -c "
                  import tiktoken
                  encodings = ['cl100k_base', 'p50k_base', 'r50k_base']
                  for enc in encodings:
                      try:
                          tiktoken.get_encoding(enc)
                          print(f'Cached {enc} encoding')
                      except Exception as e:
                          print(f'Warning: Could not cache {enc}: {e}')
                  print('Tiktoken pre-download complete')
                  "
            build:
              commands:
                - echo Build started on `date`
                - echo Building the Docker image...
                - cd src
                - |
                  if [ "$ENABLE_MULTI_ARCH" = "true" ]; then
                    # Multi-architecture build
                    echo "Building multi-architecture image..."
                    docker buildx build \
                      --platform linux/amd64,linux/arm64 \
                      --build-arg TIKTOKEN_CACHE_DIR=/app/tiktoken_cache \
                      -t $REPOSITORY_URI:$IMAGE_TAG \
                      -t $REPOSITORY_URI:$IMAGE_TAG_COMMIT \
                      -f Dockerfile_ecs \
                      --push .
                  else
                    # Single architecture build
                    echo "Building single architecture image for $BUILD_ARCH..."
                    docker build \
                      --platform $BUILD_ARCH \
                      --build-arg TIKTOKEN_CACHE_DIR=/app/tiktoken_cache \
                      --build-arg BUILDKIT_INLINE_CACHE=1 \
                      -t $REPOSITORY_URI:$IMAGE_TAG \
                      -t $REPOSITORY_URI:$IMAGE_TAG_COMMIT \
                      -f Dockerfile_ecs .
                    
                    # Push images
                    docker push $REPOSITORY_URI:$IMAGE_TAG
                    docker push $REPOSITORY_URI:$IMAGE_TAG_COMMIT
                  fi
            post_build:
              commands:
                - echo Build completed on `date`
                - echo Pushing the Docker image...
                - echo "Image pushed to $REPOSITORY_URI:$IMAGE_TAG"
                - echo "Image also tagged as $REPOSITORY_URI:$IMAGE_TAG_COMMIT"
      SourceVersion: !Sub "refs/heads/${GitHubBranch}"
      TimeoutInMinutes: 60
      Tags:
        - Key: Name
          Value: !Ref ProjectName

  # ================================
  # Custom Dockerfile with Tiktoken Caching
  # ================================
  TiktokenOptimizedDockerfile:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ProjectName}-dockerfile-generator"
      Description: "Generate optimized Dockerfile with local tiktoken caching"
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      Source:
        Type: NO_SOURCE
        BuildSpec: |
          version: 0.2
          phases:
            build:
              commands:
                - |
                  cat > /tmp/Dockerfile_ecs_optimized << 'EOF'
                  FROM public.ecr.aws/docker/library/python:3.12-slim

                  WORKDIR /app

                  # Install system dependencies
                  RUN apt-get update && apt-get install -y --no-install-recommends \
                      build-essential \
                      curl \
                      && rm -rf /var/lib/apt/lists/*

                  # Copy requirements first for better caching
                  COPY ./requirements.txt /app/requirements.txt

                  # Install Python dependencies
                  RUN pip install --no-cache-dir -r requirements.txt

                  # Create tiktoken cache directory
                  ARG TIKTOKEN_CACHE_DIR=/app/tiktoken_cache
                  RUN mkdir -p ${TIKTOKEN_CACHE_DIR}
                  ENV TIKTOKEN_CACHE_DIR=${TIKTOKEN_CACHE_DIR}

                  # Pre-download tiktoken encodings during build
                  RUN python -c "import tiktoken; \
                      encodings = ['cl100k_base', 'p50k_base', 'r50k_base']; \
                      [tiktoken.get_encoding(enc) for enc in encodings]; \
                      print('Tiktoken encodings cached successfully')"

                  # Copy application code
                  COPY . /app/

                  # Set environment variables
                  ENV PYTHONPATH=/app
                  ENV TIKTOKEN_CACHE_DIR=${TIKTOKEN_CACHE_DIR}

                  # Expose port
                  EXPOSE 8080

                  # Health check
                  HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
                    CMD curl -f http://localhost:8080/health || exit 1

                  # Run the application
                  CMD ["python", "app.py"]
                  EOF
                - echo "Optimized Dockerfile generated successfully"
                - echo "This Dockerfile includes local tiktoken caching for faster builds"
      TimeoutInMinutes: 10
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-dockerfile-generator"

Outputs:
  CodeBuildProjectName:
    Description: Name of the CodeBuild project
    Value: !Ref CodeBuildProject
    Export:
      Name: !Sub "${AWS::StackName}-CodeBuildProject"

  ECRRepositoryName:
    Description: Name of the ECR repository
    Value: !Ref ECRRepository
    Export:
      Name: !Sub "${AWS::StackName}-ECRRepository"

  ECRRepositoryURI:
    Description: URI of the ECR repository
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepositoryName}"
    Export:
      Name: !Sub "${AWS::StackName}-ECRRepositoryURI"

  DockerfileGeneratorProject:
    Description: Name of the Dockerfile generator project
    Value: !Ref TiktokenOptimizedDockerfile
    Export:
      Name: !Sub "${AWS::StackName}-DockerfileGenerator"

  OptimizedDockerfileInfo:
    Description: Information about the tiktoken-optimized Dockerfile
    Value: "Use the generated optimized Dockerfile for better local tiktoken caching performance"